spring.application.name=codechef

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:codechefdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=8050@Pra

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Server port
server.port=8095

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false
